version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u162-jdk-node-browsers
    steps:
      - checkout
      - run: mvn
  test:
    docker:
      - image: circleci/openjdk:8-jdk-node-browsers
    steps:
      - checkout
      - run: mvn --version
  build2:
    docker:
      - image: circleci/openjdk:8u162-jdk-node-browsers
    steps:
      - checkout
      - run: javac
  test2:
    docker:
      - image: circleci/openjdk:8-jdk-node-browsers
    steps:
      - checkout
      - run: stack
  build3:
    docker:
      - image: circleci/openjdk:8u162-jdk-node-browsers
    steps:
      - checkout
      - run: jps -vm
  test3:
    docker:
      - image: circleci/openjdk:8-jdk-node-browsers
    steps:
      - checkout
      - run: java -version
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
      - build2
      - test2
      - build3
      - test3

# version: 2
# jobs:
#   build:
#     machine: true
#     parallelism: 4
#     java:
#       version: oraclejdk8
#     steps:
#       - checkout
#       - run: git clone https://github.com/checkstyle/contribution
#       - restore_cache:
#           key: goovy-binaries
#       - run: java -version
#       #- run: mvn --version
#       #- run: if [ ! -d groovy-2.4.7 ]; then wget https://dl.bintray.com/groovy/maven/apache-groovy-binary-2.4.7.zip && unzip apache-groovy-binary-2.4.7.zip; fi
#       - run: pwd
#       #- run: java -version
#       - run:
#           command: |
#             echo $(ls -1 .ci/*.sh | circleci tests split)
#             eval $(ls -1 .ci/*.sh | circleci tests split)
#       - save_cache:
#           key: goovy-binaries
#           paths:
#             - groovy-2.4.7
  # test:
  #   machine: true
  #   parallelism: 4
  #   steps:
  #     - run:
  #       command: |
  #           echo $(circleci tests glob ".ci/*.sh" | circleci tests split < $(ls -1 .ci/*.sh))
  #           eval $(circleci tests glob ".ci/*.sh" | circleci tests split < $(ls -1 .ci/*.sh))

