version: 2
jobs:
  build_cache:
    machine: true
    java:
      version: oraclejdk8
    steps:
      - checkout
      - run: git clone https://github.com/checkstyle/contribution
      - run: java -version
      - run: mvn --version
      - run: groovy --version | cat
      - run: if [ ! -d groovy-2.4.7 ]; then wget https://dl.bintray.com/groovy/maven/apache-groovy-binary-2.4.7.zip && unzip apache-groovy-binary-2.4.7.zip; fi
      - run: pwd
      - run:
        command: |
          cd contribution/checkstyle-tester
          sed -i'' 's/^guava/#guava/' projects-to-test-on.properties
          echo 'class ClassEmpty{}' > src/main/java/EmptyClass.java
          groovy-2.4.7/bin/groovy launch.groovy --listOfProjects projects-to-test-on.properties --config my_check.xml
      - save_cache:
          key: goovy-binaries-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - groovy-2.4.7
  test1:
    machine: true
    java:
      version: oraclejdk8
    steps:
      - restore_cache:
          key: goovy-binaries-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          command: |
            pwd
            ls -la
            cd contribution/checkstyle-tester
            sed -i'' 's/#protonpack/protonpack/' projects-for-circle.properties
            groovy-2.4.7/bin/groovy launch.groovy --listOfProjects projects-for-circle.properties --config checks-nonjavadoc-error.xml
  test2:
    machine: true
    java:
      version: oraclejdk8
    steps:
      - restore_cache:
          key: goovy-binaries-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          command: |
            cd contribution/checkstyle-tester
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_cache
      - test1
          requires:
            - build_cache
      - test2
          requires:
            - build_cache

